<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '12',
    'typeid' => '0',
    'title' => '创业者之大忌：崇尚强权而不自省【读历史知创业】',
    'style' => '',
    'thumb' => 'http://phpcms/uploadfile/2015/1015/20151015034714510.jpg',
    'keywords' => '强权 大忌 创业者',
    'description' => '导语：看看你是不是这样：不能批评、讳疾忌医、死不认错、文过饰非、蒙混过关、以退为进。创业团队整体性的反省精神和能力某种意义上决定了这个企业的格局。',
    'posids' => '1',
    'url' => 'http://phpcms/index.php?m=content&c=index&a=show&catid=12&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1444895131',
    'updatetime' => '1444895293',
    'hitsid' => 'c-1-1',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '12',
    'typeid' => '0',
    'title' => '创业竞争日益白热化 "天使"在早期投资将扮演更重要角色',
    'style' => '',
    'thumb' => 'http://phpcms/uploadfile/2015/1015/20151015035017649.jpg',
    'keywords' => '角色 天使',
    'description' => '导语：如果新创团队可以找到一群有相关资源跟经验的天使当作早期投资人，所发挥的综效是远超过传统创投的，也可以加速团队的成长和扩张。',
    'posids' => '1',
    'url' => 'http://phpcms/index.php?m=content&c=index&a=show&catid=12&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1444895332',
    'updatetime' => '1444895427',
    'hitsid' => 'c-1-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>