<?php
return array (
  777 => 
  array (
    'id' => '777',
    'catid' => '23',
    'typeid' => '0',
    'title' => '手游生态 巨头称霸下迎来创业者破局',
    'style' => '',
    'thumb' => 'http://phpcms/uploadfile/2015/1026/20151026102602642.jpg',
    'keywords' => '手游 创业者  生态',
    'description' => '说到中国的手游格局，不得不提手游产业链的三大环节，研发商、发行商和渠道商，正是这三大环节决定了今天中国手游市场的格局。研发商中，以   ',
    'posids' => '1',
    'url' => 'http://phpcms/index.php?m=content&c=index&a=show&catid=23&id=777',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '0',
    'islink' => '0',
    'username' => 'aaa@163.com',
    'inputtime' => '1445826360',
    'updatetime' => '1445907300',
    'hitsid' => 'c-1-777',
    'views' => '17',
    'yesterdayviews' => '16',
    'dayviews' => '1',
    'weekviews' => '17',
    'monthviews' => '17',
  ),
  776 => 
  array (
    'id' => '776',
    'catid' => '23',
    'typeid' => '0',
    'title' => 'O2O方程式解密：看懂它，就知道谁会死',
    'style' => '',
    'thumb' => 'http://phpcms/uploadfile/2015/1024/20151024030100616.jpg',
    'keywords' => '方程式 O2O',
    'description' => '天天看到各种O2O死亡名单，你是不是也快麻木了？也不知道这些名单是哪里来的啊。不过看看以下文章中，各位牛咖对O2O的大话，你可能能兴奋起来了。',
    'posids' => '0',
    'url' => 'http://phpcms/index.php?m=content&c=index&a=show&catid=23&id=776',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1445669940',
    'updatetime' => '1445826780',
    'hitsid' => 'c-1-776',
    'views' => '4',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '4',
  ),
  774 => 
  array (
    'id' => '774',
    'catid' => '23',
    'typeid' => '0',
    'title' => '社交电商，微信还有很长的路要走',
    'style' => '',
    'thumb' => 'http://phpcms/uploadfile/2015/1024/20151024025608116.jpg',
    'keywords' => '电商 社交微信',
    'description' => '虽然很多创业者都知道社交电商是移动电商的下一波浪潮，但是绝大多数不是心有余而力不足就是驻足观望。',
    'posids' => '1',
    'url' => 'http://phpcms/index.php?m=content&c=index&a=show&catid=23&id=774',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1445669580',
    'updatetime' => '1445826534',
    'hitsid' => 'c-1-774',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '3',
  ),
  775 => 
  array (
    'id' => '775',
    'catid' => '23',
    'typeid' => '0',
    'title' => '降息来临，互联网金融从高收益大战转向安全大战',
    'style' => '',
    'thumb' => 'http://phpcms/uploadfile/2015/1024/20151024025852794.jpg',
    'keywords' => '收益 银行 存款',
    'description' => '近日，随着央行降息的到来，不管是银行理财、第三方支付类理财还是P2P类高收益的平台都开始出现了综合收益明显下降的情况。',
    'posids' => '1',
    'url' => 'http://phpcms/index.php?m=content&c=index&a=show&catid=23&id=775',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1445669820',
    'updatetime' => '1445907333',
    'hitsid' => 'c-1-775',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '3',
  ),
);
?>